logpath: /home/pi/Waterflow/waterflow.log
lastprogrampath:
valves:
  - name: main
    pin: 35
  - name: grass
    pin: 36

programs:
  - start_time : 10:51:00
    valves_times:
      - 1
      - 2
  - start_time : 14:02:00
    valves_times:
      - 2
      - 3