logpath: waterflow.log
lastprogrampath: lastprogram.yml
valves:
  - name: main
    pin: 33
  - name: grass
    pin: 35

programs:
  - start_time: '10:51:00'
    valves_times:
      - 1
      - 2
  - start_time: '17:08:00'
    valves_times:
      - 1
      - 1
