lastprogrampath: lastprogram.yml
logpath: waterflow.log
loop_freq: 1
programs:
- start_time: '09:51:00'
  valves_times:
  - 1
  - 2
- start_time: '19:43:00'
  valves_times:
  - 1
  - 1
valves:
- name: main
  pin: 33
- name: grass
  pin: 35
